dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
before_install:
  - pip install -U pip
  - pip install -q -r fn-sinesp/requirements.txt
before_script:
  - flake8 fn-sinesp/
script:
  - pytest
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop